"""Initial setup with unique titles

Revision ID: 3a5f287d1cfc
Revises: 
Create Date: 2026-07-06 13:03:57.257775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3a5f287d1cfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Canonical problem identifier'),
    sa.Column('title', sa.String(), nullable=False, comment="Short internal name, e.g. 'Two Sum'"),
    sa.Column('statement', sa.Text(), nullable=False, comment='Original, undisguised problem statement shown only internally'),
    sa.Column('signature', sa.JSON(), server_default='{}', nullable=False, comment='Strict I/O typing (function name, args, returns) to enforce LLM boundaries'),
    sa.Column('constraints', sa.JSON(), nullable=False, comment='Input bounds and edge-case rules the translation must preserve exactly'),
    sa.Column('reference_solution', sa.Text(), nullable=False, comment='Known-correct solution, used to validate translated variants'),
    sa.Column('test_cases', sa.JSON(), nullable=False, comment='Hidden test suite; never shown to the candidate'),
    sa.Column('difficulty', sa.String(), nullable=False, comment='e.g. easy / medium / hard'),
    sa.Column('tags', sa.JSON(), nullable=False, comment="Topic tags for randomization, e.g. ['arrays', 'hash-map']"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('problem_variants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False, comment='Source canonical problem this variant was translated from'),
    sa.Column('translated_statement', sa.Text(), nullable=False, comment='LLM-generated disguised version shown to the candidate'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment='Embedding of translated_statement, used for scenario grounding + dedup checks'),
    sa.Column('validated', sa.Boolean(), server_default='false', nullable=False, comment="True once the reference solution has passed against this variant's re-derived test cases"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('problem_variant_id', sa.UUID(), nullable=False, comment='Which disguised variant this interview session used'),
    sa.Column('status', sa.String(), server_default='pending', nullable=False, comment='pending / active / completed / abandoned'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['problem_variant_id'], ['problem_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('problem_variants')
    op.drop_table('problems')
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
    # ### end Alembic commands ###
