"""Improve problem variants

Revision ID: 3d78ae26d8e6
Revises: 3a5f287d1cfc
Create Date: 2026-07-07 18:01:39.184405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '3d78ae26d8e6'
down_revision: Union[str, Sequence[str], None] = '3a5f287d1cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_variants', sa.Column('scenario_context', sa.Text(), nullable=False, comment="The overarching theme (e.g., 'Logistics coordinator for space cargo')"))
    op.add_column('problem_variants', sa.Column('stage_1_mvp', sa.Text(), nullable=False, comment='The initial coding task (Disguised LeetCode)'))
    op.add_column('problem_variants', sa.Column('stage_2_curveball', sa.Text(), nullable=False, comment='The sudden requirement change to test adaptability'))
    op.add_column('problem_variants', sa.Column('stage_3_system', sa.Text(), nullable=False, comment='The architecture/scaling discussion prompt'))
    op.add_column('problem_variants', sa.Column('technical_rubric', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Time/space tradeoffs, expected data structures, edge cases to catch'))
    op.add_column('problem_variants', sa.Column('system_rubric', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Expected system design concepts (e.g., Redis, Sharding, CAP theorem)'))
    op.add_column('problem_variants', sa.Column('communication_rubric', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Questions they should have asked, testing strategies they should suggest'))
    op.alter_column('problem_variants', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               comment='Embedding of the scenario_context for dedup checks',
               existing_comment='Embedding of translated_statement, used for scenario grounding + dedup checks',
               existing_nullable=True)
    op.alter_column('problem_variants', 'validated',
               existing_type=sa.BOOLEAN(),
               comment='True once the reference solution has passed',
               existing_comment="True once the reference solution has passed against this variant's re-derived test cases",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('problem_variants_problem_id_fkey'), 'problem_variants', type_='foreignkey')
    op.create_foreign_key(None, 'problem_variants', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem_variants', type_='foreignkey')
    op.create_foreign_key(op.f('problem_variants_problem_id_fkey'), 'problem_variants', 'problems', ['problem_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('problem_variants', 'validated',
               existing_type=sa.BOOLEAN(),
               comment="True once the reference solution has passed against this variant's re-derived test cases",
               existing_comment='True once the reference solution has passed',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('problem_variants', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               comment='Embedding of translated_statement, used for scenario grounding + dedup checks',
               existing_comment='Embedding of the scenario_context for dedup checks',
               existing_nullable=True)
    op.drop_column('problem_variants', 'communication_rubric')
    op.drop_column('problem_variants', 'system_rubric')
    op.drop_column('problem_variants', 'technical_rubric')
    op.drop_column('problem_variants', 'stage_3_system')
    op.drop_column('problem_variants', 'stage_2_curveball')
    op.drop_column('problem_variants', 'stage_1_mvp')
    op.drop_column('problem_variants', 'scenario_context')
    # ### end Alembic commands ###
