"""Change vector size to 768

Revision ID: 4cf2e7f46298
Revises: d51eea5c1fa5
Create Date: 2026-07-06 12:43:01.426307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '4cf2e7f46298'
down_revision: Union[str, Sequence[str], None] = 'd51eea5c1fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem_variants', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_comment='Embedding of translated_statement, used for scenario grounding + dedup checks',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem_variants', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_comment='Embedding of translated_statement, used for scenario grounding + dedup checks',
               existing_nullable=True)
    # ### end Alembic commands ###
