"""Add signature columnto avoid drift

Revision ID: 790c788772a9
Revises: 4cf2e7f46298
Create Date: 2026-07-06 12:55:57.944595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790c788772a9'
down_revision: Union[str, Sequence[str], None] = '4cf2e7f46298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('signature', sa.JSON(), server_default='{}', nullable=False, comment='Strict I/O typing (function name, args, returns) to enforce LLM boundaries'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'signature')
    # ### end Alembic commands ###
