"""fix problem variants schema

Revision ID: a26e6bf2670b
Revises: 3d78ae26d8e6
Create Date: 2026-07-07 18:35:47.114732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26e6bf2670b'
down_revision: Union[str, Sequence[str], None] = '3d78ae26d8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem_variants', 'translated_statement')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_variants', sa.Column('translated_statement', sa.TEXT(), autoincrement=False, nullable=False, comment='LLM-generated disguised version shown to the candidate'))
    # ### end Alembic commands ###
