"""add problem_id to sessions

Revision ID: d2054f3c4d28
Revises: a26e6bf2670b
Create Date: 2026-07-13 13:35:12.002194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2054f3c4d28'
down_revision: Union[str, Sequence[str], None] = 'a26e6bf2670b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('problem_id', sa.UUID(), nullable=False, comment='Direct reference to base problem to avoid waterfall queries'))
    op.create_foreign_key(None, 'sessions', 'problems', ['problem_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'problem_id')
    # ### end Alembic commands ###
